export interface Props {
  disabled?: boolean,
  bold?: boolean,
  borderRadius?: number,
  fontSize?: number,
  height?: number,
  width?: number,
  margin?: string,
  text: string,
  color?: string,
  background?: string,
  cursor?: string,
  onClick?: () => void,
  hover?: string,
  active?: string,
}

export interface Style {
  bold?: boolean,
  borderRadius?: number,
  fontSize?: number,
  height?: number,
  width?: number,
  margin?: string,
  color?: string,
  background?: string,
  cursor?: string,
  hover?: string,
  active?: string,
}
